name: Build Pro Monitor
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.19.3'
      - name: Fix Manifest & Permissions
        run: |
          flutter create . --platforms android
          sed -i 's/<application/<application android:usesCleartextTraffic="true"/' android/app/src/main/AndroidManifest.xml
          sed -i '/<\/manifest>/i <uses-permission android:name="android.permission.INTERNET" \/><uses-permission android:name="android.permission.CAMERA" \/>' android/app/src/main/AndroidManifest.xml
      - run: flutter pub add mobile_scanner web_socket_channel
      - run: flutter build apk --release
      - uses: actions/upload-artifact@v4
        with:
          name: Pro-Monitor-APK
          path: build/app/outputs/flutter-apk/app-release.apk
